basic:
	cd uartd; make
	cd soundd; make
	cd usbhostd; make
	cd hid_keybd; make
	cd hid_joystickd; make
	cd spi2uart; make

gui:
	cd fbd; make
	cd dsi_fbd; make
	cd hid_moused; make
	cd hid_touchd; make

network:
	cd wlan; make
	cd btd; make

clean:	
	cd uartd; make clean
	cd fbd; make clean
	cd dsi_fbd; make clean
	cd soundd; make clean
	cd usbhostd; make clean
	cd hid_keybd; make clean
	cd hid_moused; make clean
	cd hid_touchd; make clean
	cd hid_joystickd; make clean
	cd spi2uart; make clean
	cd wlan; make clean
	cd btd; make clean
