basic:
	cd ttyd; $(MAKE)
	cd powerd; $(MAKE)

gui:
	cd fbd; $(MAKE)
	cd usbd; $(MAKE)
	cd usbkeybd; $(MAKE)
	cd usbmoused; $(MAKE)
	cd ps2keybd; $(MAKE)
	cd ps2moused; $(MAKE)

network:

clean:
	cd ttyd; $(MAKE) clean
	cd powerd; $(MAKE) clean
	cd fbd; $(MAKE) clean
	cd usbd; $(MAKE) clean
	cd usbkeybd; $(MAKE) clean
	cd usbmoused; $(MAKE) clean
	cd ps2keybd; $(MAKE) clean
	cd ps2moused; $(MAKE) clean
