basic:
	cd ttyd; make
	cd powerd; make

gui:
	cd fbd; make
	cd usbd; make
	cd usbkeybd; make
	cd usbmoused; make
	cd ps2keybd; make
	cd ps2moused; make

network:

clean:
	cd ttyd; make clean
	cd powerd; make clean
	cd fbd; make clean
	cd usbd; make clean
	cd usbkeybd; make clean
	cd usbmoused; make clean
	cd ps2keybd; make clean
	cd ps2moused; make clean
