basic:
	cd ttyd; make
	cd powerd; make

gui:
	cd fbd; make
	cd ps2keybd; make
	cd ps2moused; make

network:

clean:
	cd ttyd; make clean
	cd powerd; make clean
	cd fbd; make clean
	cd ps2keybd; make clean
	cd ps2moused; make clean
