all: 
	cd audio; $(MAKE)
	cd fbdisplayd; $(MAKE)
	cd g2dd; $(MAKE)
	cd gpio_joystickd; $(MAKE)
	cd ms_uartd; $(MAKE)

clean:	
	cd audio; $(MAKE) clean
	cd fbdisplayd; $(MAKE) clean
	cd g2dd; $(MAKE) clean
	cd gpio_joystickd; $(MAKE) clean
	cd ms_uartd; $(MAKE) clean
