all: 
	cd fbdisplayd; $(MAKE)
	cd uartd; $(MAKE)
	cd gpio_joystickd; $(MAKE)
	cd adcd; $(MAKE)

clean:	
	cd fbdisplayd; $(MAKE) clean
	cd uartd; $(MAKE) clean
	cd gpio_joystickd; $(MAKE) clean
	cd adcd; $(MAKE) clean
