basic: 
	cd ttyd; $(MAKE)
	cd powerd; $(MAKE)
	cd ps2keybd; $(MAKE)
	cd smc91c111d; $(MAKE)

gui:
	cd fbdisplayd; $(MAKE)
	cd ps2moused; $(MAKE)

clean:	
	cd ttyd; $(MAKE) clean
	cd powerd; $(MAKE) clean
	cd fbdisplayd; $(MAKE) clean
	cd ps2keybd; $(MAKE) clean
	cd ps2moused; $(MAKE) clean
	cd smc91c111d; $(MAKE) clean
