#ifndef G2D_QPU_KERNELS_V42_H
#define G2D_QPU_KERNELS_V42_H

#include <stdint.h>

/* Generated by qpuasm -v 42 -p v42_.  These declarations intentionally
 * live separately from the V3D 7.1 arrays so runtime version selection is
 * explicit and a BCM2711 can never execute a Pi 5 instruction stream. */
extern const uint64_t g2d_qpu_v42_argb_fill[];
extern const unsigned g2d_qpu_v42_argb_fill_n;
extern const uint64_t g2d_qpu_v42_argb_blit[];
extern const unsigned g2d_qpu_v42_argb_blit_n;
extern const uint64_t g2d_qpu_v42_argb_rotate[];
extern const unsigned g2d_qpu_v42_argb_rotate_n;
extern const uint64_t g2d_qpu_v42_argb_rot90[];
extern const unsigned g2d_qpu_v42_argb_rot90_n;
extern const uint64_t g2d_qpu_v42_argb_rot90_tile[];
extern const unsigned g2d_qpu_v42_argb_rot90_tile_n;
extern const uint64_t g2d_qpu_v42_argb_rot90_vpm[];
extern const unsigned g2d_qpu_v42_argb_rot90_vpm_n;
extern const uint64_t g2d_qpu_v42_argb_alpha[];
extern const unsigned g2d_qpu_v42_argb_alpha_n;
extern const uint64_t g2d_qpu_v42_argb_scale_pow2[];
extern const unsigned g2d_qpu_v42_argb_scale_pow2_n;
extern const uint64_t g2d_qpu_v42_v42_store[];
extern const unsigned g2d_qpu_v42_v42_store_n;

#endif
