basic:
	cd uartd; $(MAKE)
	cd fand; $(MAKE)
	cd cpud; $(MAKE)
	cd nvmefsd; $(MAKE)

network:
	cd wlan; $(MAKE)

gui:
	cd fbdisplayd; $(MAKE)
	cd usbhostd; $(MAKE)
	cd hid_keybd; $(MAKE)
	cd hid_moused; $(MAKE)
	cd hid_touchd; $(MAKE)
	cd gt911_touchd; $(MAKE)

clean:
	cd uartd; $(MAKE) clean
	cd fand; $(MAKE) clean
	cd cpud; $(MAKE) clean
	cd nvmefsd; $(MAKE) clean
	cd fbdisplayd; $(MAKE) clean
	cd usbhostd; $(MAKE) clean
	cd hid_keybd; $(MAKE) clean
	cd hid_moused; $(MAKE) clean
	cd hid_touchd; $(MAKE) clean
	cd gt911_touchd; $(MAKE) clean
	cd wlan; $(MAKE) clean
